routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return redirect()->route('dashboard');
});

Route::get('dashboard/{date?}', 'DashboardController')
    ->name('dashboard');

Route::resource('produtos', 'ProductsController');

Route::post('produtos/{produto}/adicionar-produtos', 'ProductStockAddController')
    ->name('produtos.add-stock');

Route::post('produtos/{produto}/baixar-produtos', 'ProductStockRemoveController')
    ->name('produtos.remove-stock');

Auth::routes();

resources/views/stock/alert-table-compact.blade.php
{{-- Tabela com produtos cadastrados --}}

<div class="list-group">
    @forelse($products as $product)
    <a href="{{ route('produtos.show', $product->sku) }}" class="list-group-item list-group-item-action">
        {{ $product->sku }}
        <span class="badge badge-danger badge-pill">
            {{ $product->quantity }}
        </span>
    </a>
    @empty
    <div class="list-group-item">
        Nenhum alerta.
    </div>
    @endforelse
</div>

resources/views/stock/table-daily-compact.blade.php
<div class="list-group">
    @forelse($stocks as $stock)
    <a href="{{ route('produtos.show', $stock->product->sku) }}" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">{{ $stock->product->name }}</h5>
          <small>{{ $stock->method }}</small>
        </div>
        <p class="mb-1">
            {{ $stock->product->sku }}
        </p>
        <small class="text-{{ $stock->type == 'in' ? 'success' : 'danger' }}">Quantidade: {{ $stock->quantity }}</small>
    </a>
    @empty
    <div class="list-group-item">
        Nenhum produto cadastrado neste dia
    </div>
    @endforelse
</div>